version: 2

sources:
  - name: raw
    database: bike
    schema: raw
    tables:
      - name: raw_trip_data


models:
  - name: stg_fact_trip
    description:  Ingest of raw data.

    columns:
      - name: datetime
        description: Time of measurement (lowest granularity 1 hour)
        tests:
          - not_null
      - name: station_trips
        description: Count of trips within the hour
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

  - name: fact_hourly_trips
    description: "This model extracts and transforms trip data including datetime components."

    columns:
      - name: datetime
        description: "The timestamp of the trip."
        tests:
          - not_null
          - unique

      - name: station_trips
        description: "The number of trips at the station for the given datetime."
        tests:
          - not_null

      - name: year
        description: "The year extracted from the datetime column."
        tests:
          - not_null

      - name: month
        description: "The full month name extracted from the datetime column."
        tests:
          - not_null

      - name: day_of_month
        description: "The day of the month extracted from the datetime column."
        tests:
          - not_null

      - name: days_in_month
        description: "The total number of days in the month of the datetime column."
        tests:
          - not_null

      - name: day_of_year
        description: "The day of the year extracted from the datetime column."
        tests:
          - not_null

      - name: day_of_week
        description: "The name of the day of the week extracted from the datetime column."
        tests:
          - not_null

      - name: hour
        description: "The hour of the day extracted from the datetime column."
        tests:
          - not_null


  - name: fact_trips
    description: Clean data with time features