dbt_bike:
  outputs:
    staging:
      type: duckdb
      path:  "md:bike?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 1
      schema: staging
    production:
      type: duckdb
      path:  "md:bike?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 1
      schema: production
  target: staging