version: 2

sources:
  - name: raw
    database: bike
    schema: raw
    freshness:
      warn_after:
        count: 7
        period: day
      error_after:
        count: 14
        period: day
    loaded_at_field: _etl_loaded_at
    tables:
      - name: raw_trip_data


models:
  - name: stg_fact_trip
    description:  Ingest of raw data.

    columns:
      - name: datetime
        description: Time of measurement (lowest granularity 1 hour)
        tests:
          - not_null
          - unique
      - name: station_trips
        description: Count of trips within the hour
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: fact_trips_daily
    description: "This model rolls up the trips by day."

    columns:
      - name: datetime
        description: "Day trips are measured"
        tests:
          - not_null
          - unique
      - name: station_trips
        description: Count of trips on indicated day
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: fact_smoothed_trips
    description: Rolling averages of various lengths for fact_trips_daily.

    columns:
        - name: datetime
          description: |
            The date on which the trip data was recorded. This column serves as the primary key for the model and is used to order the rows for rolling average calculations.

        - name: station_trips
          description: |
            The total number of trips recorded at each station on the given date.

        - name: station_trips_7_day_rolling_avg
          description: |
            The 7-day rolling average of the `station_trips` column. This value is calculated by averaging the number of trips for the current day and the previous six days.

        - name: station_trips_14_day_rolling_avg
          description: |
            The 14-day rolling average of the `station_trips` column. This value is calculated by averaging the number of trips for the current day and the previous thirteen days.

        - name: station_trips_30_day_rolling_avg
          description: |
            The 30-day rolling average of the `station_trips` column. This value is calculated by averaging the number of trips for the current day and the previous twenty-nine days.
