version: 2

sources:
  - name: raw
    database: bike
    schema: raw
    freshness:
      warn_after:
        count: 7
        period: day
      error_after:
        count: 14
        period: day
    loaded_at_field: _etl_loaded_at
    tables:
      - name: raw_trip_data


models:
  - name: stg_fact_trip
    description:  Ingest of raw data.

    columns:
      - name: datetime
        description: Time of measurement (lowest granularity 1 hour)
        tests:
          - not_null
          - unique
      - name: station_trips
        description: Count of trips within the hour
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

  - name: fact_trips_hourly
    description: "This model extracts and transforms trip data including datetime components."

    columns:
      - name: datetime
        description: "The timestamp of the trip."
        tests:
          - not_null
          - unique

      - name: station_trips
        description: "The number of trips at the station for the given datetime."
        tests:
          - not_null

  - name: fact_trips_daily
    description: "This model rolls up the trips by day."

    columns:
      - name: date
        description: "Day trips are measured"
        tests:
          - not_null
          - unique
      - name: station_trips
        description: Count of trips on indicated day
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      