version: 2

sources:
  - name: raw
    database: bike
    schema: raw
    freshness: 
      warn_after:
        count: 7
        period: day
      error_after:
        count: 14
        period: day
    loaded_at_field: _etl_loaded_at
    tables:
      - name: raw_weather_data
  
models:
  - name: stg_weather
    description: >
      This model processes weather data by unnesting nested arrays from the source table `raw_weather_data` into a flat table. 
      The data includes various hourly weather parameters such as temperature, humidity, wind speed, radiation, precipitation, and more.
    columns:
      - name: latitude
        description: Latitude of the weather data point.
      - name: longitude
        description: Longitude of the weather data point.
      - name: generationtime_ms
        description: Time taken to generate the weather data in milliseconds.
      - name: utc_offset_seconds
        description: UTC offset in seconds.
      - name: timezone
        description: Timezone of the weather data location.
      - name: timezone_abbreviation
        description: Abbreviation of the timezone.
      - name: elevation
        description: Elevation of the weather data location in meters.
      - name: time
        description: Timestamp for the hourly weather data.
      - name: temperature_2m
        description: Air temperature at 2 meters above ground in degrees Celsius (°C).
      - name: relative_humidity_2m
        description: Relative humidity at 2 meters above ground in percentage (%).
      - name: dew_point_2m
        description: Dew point temperature at 2 meters above ground in degrees Celsius (°C).
      - name: apparent_temperature
        description: Apparent temperature, or feels-like temperature, combining wind chill factor, humidity, and solar radiation in degrees Celsius (°C).
      - name: pressure_msl
        description: Atmospheric pressure at mean sea level in hectopascals (hPa).
      - name: surface_pressure
        description: Surface pressure in hectopascals (hPa).
      - name: cloud_cover
        description: Total cloud cover as an area fraction in percentage (%).
      - name: cloud_cover_low
        description: Low-level cloud cover (up to 3 km altitude) as an area fraction in percentage (%).
      - name: cloud_cover_mid
        description: Mid-level cloud cover (3 to 8 km altitude) as an area fraction in percentage (%).
      - name: cloud_cover_high
        description: High-level cloud cover (above 8 km altitude) as an area fraction in percentage (%).
      - name: wind_speed_10m
        description: Wind speed at 10 meters above ground in km/h (or mph, m/s, knots).
      - name: wind_speed_80m
        description: Wind speed at 80 meters above ground in km/h (or mph, m/s, knots).
      - name: wind_speed_120m
        description: Wind speed at 120 meters above ground in km/h (or mph, m/s, knots).
      - name: wind_speed_180m
        description: Wind speed at 180 meters above ground in km/h (or mph, m/s, knots).
      - name: wind_direction_10m
        description: Wind direction at 10 meters above ground in degrees (°).
      - name: wind_direction_80m
        description: Wind direction at 80 meters above ground in degrees (°).
      - name: wind_direction_120m
        description: Wind direction at 120 meters above ground in degrees (°).
      - name: wind_direction_180m
        description: Wind direction at 180 meters above ground in degrees (°).
      - name: wind_gusts_10m
        description: Maximum wind gusts at 10 meters above ground in the preceding hour in km/h (or mph, m/s, knots).
      - name: shortwave_radiation
        description: Average shortwave solar radiation in the preceding hour in watts per square meter (W/m²).
      - name: direct_radiation
        description: Average direct solar radiation in the preceding hour on the horizontal plane in watts per square meter (W/m²).
      - name: direct_normal_irradiance
        description: Average direct solar radiation in the preceding hour on the normal plane (perpendicular to the sun) in watts per square meter (W/m²).
      - name: diffuse_radiation
        description: Average diffuse solar radiation in the preceding hour in watts per square meter (W/m²).
      - name: global_tilted_irradiance
        description: Average total radiation received on a tilted plane in the preceding hour in watts per square meter (W/m²).
      - name: vapour_pressure_deficit
        description: Vapour Pressure Deficit (VPD) in kilopascals (kPa), indicating the difference between the amount of moisture in the air and the amount it can hold when saturated.
      - name: cape
        description: Convective Available Potential Energy (CAPE) in joules per kilogram (J/kg).
      - name: evapotranspiration
        description: Evapotranspiration from land surface and plants in the preceding hour in millimeters (mm).
      - name: et0_fao_evapotranspiration
        description: Reference evapotranspiration of a well-watered grass field based on FAO-56 Penman-Monteith equations in millimeters (mm).
      - name: precipitation
        description: Total precipitation in the preceding hour in millimeters (mm).
      - name: snowfall
        description: Snowfall amount in the preceding hour in centimeters (cm).
      - name: precipitation_probability
        description: Probability of precipitation in the preceding hour in percentage (%).
      - name: _etl_loaded_at
        description: Timestamp indicating when the data was loaded.

  - name: stg_dim_weather_units
    description: Units for associated measurements
    columns:
      - name: datetime
        description: "Timestamp of the data recording in UTC."
        data_type: VARCHAR
      - name: time
        description: "Array of hourly timestamps."
        data_type: VARCHAR
      - name: temperature_2m
        description: "Array of hourly temperature values at 2 meters above ground level."
        data_type: VARCHAR
      - name: relative_humidity_2m
        description: "Array of hourly relative humidity values at 2 meters above ground level."
        data_type: VARCHAR
      - name: dew_point_2m
        description: "Array of hourly dew point values at 2 meters above ground level."
        data_type: VARCHAR
      - name: apparent_temperature
        description: "Array of hourly apparent temperature values, which account for wind and humidity."
        data_type: VARCHAR
      - name: pressure_msl
        description: "Array of hourly mean sea-level pressure values."
        data_type: VARCHAR
      - name: surface_pressure
        description: "Array of hourly surface pressure values."
        data_type: VARCHAR
      - name: cloud_cover
        description: "Array of hourly cloud cover percentage values."
        data_type: VARCHAR
      - name: cloud_cover_low
        description: "Array of hourly low-level cloud cover percentage values."
        data_type: VARCHAR
      - name: cloud_cover_mid
        description: "Array of hourly mid-level cloud cover percentage values."
        data_type: VARCHAR
      - name: cloud_cover_high
        description: "Array of hourly high-level cloud cover percentage values."
        data_type: VARCHAR
      - name: wind_speed_10m
        description: "Array of hourly wind speed values at 10 meters above ground level."
        data_type: VARCHAR
      - name: wind_speed_80m
        description: "Array of hourly wind speed values at 80 meters above ground level."
        data_type: VARCHAR
      - name: wind_speed_120m
        description: "Array of hourly wind speed values at 120 meters above ground level."
        data_type: VARCHAR
      - name: wind_speed_180m
        description: "Array of hourly wind speed values at 180 meters above ground level."
        data_type: VARCHAR
      - name: wind_direction_10m
        description: "Array of hourly wind direction values at 10 meters above ground level."
        data_type: VARCHAR
      - name: wind_direction_80m
        description: "Array of hourly wind direction values at 80 meters above ground level."
        data_type: VARCHAR
      - name: wind_direction_120m
        description: "Array of hourly wind direction values at 120 meters above ground level."
        data_type: VARCHAR
      - name: wind_direction_180m
        description: "Array of hourly wind direction values at 180 meters above ground level."
        data_type: VARCHAR
      - name: wind_gusts_10m
        description: "Array of hourly wind gusts values at 10 meters above ground level."
        data_type: VARCHAR
      - name: shortwave_radiation
        description: "Array of hourly shortwave radiation values."
        data_type: VARCHAR
      - name: direct_radiation
        description: "Array of hourly direct radiation values."
        data_type: VARCHAR
      - name: direct_normal_irradiance
        description: "Array of hourly direct normal irradiance values."
        data_type: VARCHAR
      - name: diffuse_radiation
        description: "Array of hourly diffuse radiation values."
        data_type: VARCHAR
      - name: global_tilted_irradiance
        description: "Array of hourly global tilted irradiance values."
        data_type: VARCHAR
      - name: vapour_pressure_deficit
        description: "Array of hourly vapor pressure deficit values."
        data_type: VARCHAR
      - name: cape
        description: "Array of hourly convective available potential energy (CAPE) values."
        data_type: VARCHAR
      - name: evapotranspiration
        description: "Array of hourly evapotranspiration values."
        data_type: VARCHAR
      - name: et0_fao_evapotranspiration
        description: "Array of hourly ET0 values as per FAO standards."
        data_type: VARCHAR
      - name: precipitation
        description: "Array of hourly precipitation values."
        data_type: VARCHAR
      - name: snowfall
        description: "Array of hourly snowfall values."
        data_type: VARCHAR
      - name: precipitation_probability
        description: "Array of hourly precipitation probability values."
        data_type: VARCHAR
      - name: rain
        description: "Array of hourly rain values."
        data_type: VARCHAR
      - name: showers
        description: "Array of hourly shower values."
        data_type: VARCHAR
      - name: weather_code
        description: "Array of hourly weather code values representing different weather conditions."
        data_type: VARCHAR
      - name: snow_depth
        description: "Array of hourly snow depth values."
        data_type: VARCHAR
      - name: freezing_level_height
        description: "Array of hourly freezing level height values."
        data_type: VARCHAR
      - name: visibility
        description: "Array of hourly visibility values."
        data_type: VARCHAR
      - name: soil_temperature_0cm
        description: "Array of hourly soil temperature values at 0cm depth."
        data_type: VARCHAR
      - name: soil_temperature_6cm
        description: "Array of hourly soil temperature values at 6cm depth."
        data_type: VARCHAR
      - name: soil_temperature_18cm
        description: "Array of hourly soil temperature values at 18cm depth."
        data_type: VARCHAR
      - name: soil_temperature_54cm
        description: "Array of hourly soil temperature values at 54cm depth."
        data_type: VARCHAR
      - name: soil_moisture_0_to_1cm
        description: "Array of hourly soil moisture values from 0 to 1cm depth."
        data_type: VARCHAR
      - name: soil_moisture_1_to_3cm
        description: "Array of hourly soil moisture values from 1 to 3cm depth."
        data_type: VARCHAR
      - name: soil_moisture_3_to_9cm
        description: "Array of hourly soil moisture values from 3 to 9cm depth."
        data_type: VARCHAR
      - name: soil_moisture_9_to_27cm
        description: "Array of hourly soil moisture values from 9 to 27cm depth."
        data_type: VARCHAR
      - name: soil_moisture_27_to_81cm
        description: "Array of hourly soil moisture values from 27 to 81cm depth."
        data_type: VARCHAR
      - name: is_day
        description: "Array of hourly boolean values indicating if it's daytime."
        data_type: VARCHAR
      - name: _etl_loaded_at
        description: "Timestamp indicating when the data was loaded into the database."
        data_type: TIMESTAMP WITH TIME ZONE

  - name: fact_weather
    description: Cleaned weather data